### ISSUE TITLE
Produce h5 file

### ISSUE THREAD

**Issue by kangxiongbin** [whhudson/spatialTCR#2]
Hi William.H,

I just start to learn how to process single cell data and very interested in your study, T cell receptor (TCR) spatial sequences. 

I have a question that how to generate the h5 file (raw_feature_bc_matrix.h5 and filtered_feature_bc_matrix.h5) with matrix, feature and barcode file? I wanna produce h5 for other data in your paper (star protocol).

Look forward to your reply. Thank you very much!

Best wishes,
Xiongbin

**Comment by whhudson** [comment]
Hi Xiongbin,

The h5 files are generated by 10x Genomics' program, Space Ranger, upon alignment of the raw sequencing data. You can find the raw sequencing data, as well as the filtered feature barcode files, at the Gene Expression Omnibus under accession GSE179572. Thanks for your interest in our study.

Best,
Will
