### ISSUE TITLE
Update code to run on mixcr v4.3.2; reduce trimming quality threshold

### ISSUE THREAD

**Issue by abyappan** [whhudson/spatialTCR#3]
Hi,

I was able to get the code working for mixcr v.3.0.13 with the provided sample data for the paper; however, the code results in the an error message when running on the newest version of mixcr (v4.3.2):

**Code:** 
(I did double check and this code runs fine on mixcr v3.0.13)

`mixcr analyze shotgun -s hsa --starting-material rna --align "-OsaveOriginalReads=true" --assemble "--write-alignments" miXCR_paper_data/pt16_downsample_L001_R2_001.fastq.gz miXCR_paper_data/clones`

**Error message:**
`Unknown options: '--starting-material', '--align', '-OsaveOriginalReads=true', '--assemble', '--write-alignments', 'miXCR_paper_data/pt16_downsample_L001_R2_001.fastq.gz', 'miXCR_paper_data/clones'`

Additionally, would you please help me to update the code to include another parameter `--trimming-quality-threshold <n>` from the `align` command?

**Comment by whhudson** [comment]
Hi abyappan,

I haven't yet run this pipeline using the newest version of MiXCR, so I'm not able to update the code at this point. I hope to return to this at some point in the future, and will update the code here if I do change to MiXCR v4. Thanks for your interest.
